pref("extensions.easymath.hideCommon", false);
pref("extensions.easymath.hideComparison", false);
pref("extensions.easymath.hideFractions", false);
pref("extensions.easymath.hideSuperscript", false);
pref("extensions.easymath.hideArrows", false);
pref("extensions.easymath.hideOther", false);
pref("extensions.easymath.hideGreek", false);
pref("extensions.easymath.hideSpecific", false);
//                                 ΑαΒβΓγΔδΕεΖζΗηΘθΙιΚκΛλΜμΝνΞξΟοΠπΡρΣσΤτΥυΦφΧχΨψΩω
pref("extensions.easymath.greek", "010100000000000000000000000000010100000000000010");
